### ISSUE TITLE
mvn exec issue

### ISSUE THREAD

**Issue by wedob13** [amzn/alexa-avs-raspberry-pi#111]
Hey guys. I tried clean install of OS and doing project from the begging with more attention.

Everything works great now! I run validate and install and i get successful builds. But mvn exec:exec gives me 

INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: The KeyStore for contacting the Companion Service could not be loaded.
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:131)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.<init>(CompanionServiceClient.java:67)
	at com.amazon.alexa.avs.auth.AuthSetup.startProvisioningThread(AuthSetup.java:81)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
Caused by: java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2015)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:110)
	... 5 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
	... 8 more

any ideas? thank you

**Comment by pvasic26** [comment]
How did you solve the issue?

**Comment by wedob13** [comment]
fresh install of OS on raspberry pi.
make sure correct timezone and locale options when you generate the certificate.
double check all private/public keys and keystore phrase.
