### ISSUE TITLE
Failing after "device tokens ready"

### ISSUE THREAD

**Issue by aj770077** [amzn/alexa-avs-raspberry-pi#131]
So, everything works fine up until the mvn exec:exec    This command runs successfully and gives me the localhost address for the device tokens and such, and there it says "device tokens ready".  When hitting "ok" on the java application, it causes errors in the terminal running the app, and i dont get a bearer token in the application.  I have the companion service running and listening on port 3000, and chmod 777 on the entire folder.  Not quite sure where to start looking to fix this problem.

The following is the log:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
06:09:22.952 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
java.lang.RuntimeException: The required file config.json could not be updated.
	at com.amazon.alexa.avs.config.DeviceConfigUtils.updateConfigFile(DeviceConfigUtils.java:146) ~[classes/:?]
	at com.amazon.alexa.avs.config.DeviceConfig.saveConfig(DeviceConfig.java:204) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:59) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:90) [classes/:?]
Caused by: java.io.FileNotFoundException: config.json (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_77]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_77]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_77]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101) ~[?:1.8.0_77]
	at com.amazon.alexa.avs.config.DeviceConfigUtils.updateConfigFile(DeviceConfigUtils.java:131) ~[classes/:?]

**Comment by ajotwani** [comment]
Added an FAQ for "Companion Service" errors. See https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors. Scroll all the way down.

**Comment by keleric** [comment]
It looks like your config.json file doesn't have proper permissions (or is missing). Check that it's read and writable.

**Comment by ajotwani** [comment]
@aj770077 can you confirm if you are still having an issue?

**Comment by aj770077** [comment]
I fixed it with a "sudo env "PATH=$PATH" mvn exec:exec" command

**Comment by ajotwani** [comment]
Closing as resolved.

**Comment by rgruskin** [comment]
I am having the same issue but no luck.  Can you explain the PATH=$PATH command more? It doesn't seem to work for me?  The file config.json seems to be read and writeable.  I have been looking at this for hours now.  Help.

**Comment by aj770077** [comment]
just when it asks you to mvn anything, you do:

sudo env "PATH=$PATH" <insert mvn command here>

That's what fixed it for me

**Comment by rgruskin** [comment]
Thanks.  Also had to chmod 777 config.json.  It works!
