### ISSUE TITLE
concurrent.ExecutionException

### ISSUE THREAD

**Issue by mkarliner** [amzn/alexa-avs-raspberry-pi#147]
I've gone through all the steps and got to a supposedly working system.
When asked What's the weather in seattle? I get:

ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:264) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:60) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:214) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:210) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:29) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:220) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:60) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:491) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:251) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:260) ~[classes/:?]
	... 7 more
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_77]
	at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_77]
	at com.amazon.alexa.avs.http.MultipartContentProvider$IteratorOfIterators.next(MultipartContentProvider.java:190) ~[classes/:?]
	at com.amazon.alexa.avs.http.MultipartContentProvider$IteratorOfIterators.next(MultipartContentProvider.java:190) ~[classes/:?]
	at com.amazon.alexa.avs.http.MultipartContentProvider$MultipartIterator.next(MultipartContentProvider.java:153) ~[classes/:?]
	at com.amazon.alexa.avs.http.MultipartContentProvider$MultipartIterator.next(MultipartContentProvider.java:129) ~[classes/:?]
	at org.eclipse.jetty.client.HttpContent.advance(HttpContent.java:145) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpContent.advance(HttpContent.java:138) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpSender$ContentCallback.process(HttpSender.java:813) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:365) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpSender$ContentCallback.succeeded(HttpSender.java:869) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Session$DataEntry.succeeded(HTTP2Session.java:1226) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:274) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:332) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:253) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Flusher.window(HTTP2Flusher.java:69) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Session.onWindowUpdate(HTTP2Session.java:773) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Session.onWindowUpdate(HTTP2Session.java:411) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.BodyParser.notifyWindowUpdate(BodyParser.java:199) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.WindowUpdateBodyParser.onWindowUpdate(WindowUpdateBodyParser.java:98) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.WindowUpdateBodyParser.parse(WindowUpdateBodyParser.java:64) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]

.......

**Comment by adrianmc** [comment]
I had the same problem, but I turned up the sensitivity setting on my microphone and it worked.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by mkarliner** [comment]
What question? I don't see any questions here.

**Comment by vamsijakkula** [comment]
Today i got the same error as well .

ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException

**Comment by peternann** [comment]
I'm having this problem too. Everytime. With the current sample at with the new (at the time of writing) Wakeup word functionality.

Tried turning my microphone volume up via alsamixer, as has been suggested. No change.

The old demo worked for me a few months ago. Trying out the new functionality, but no joy.

Is there a way to debug the audio that AVS is actually getting?

**Comment by happyfrog99** [comment]
Similar/same error message - running raspbian on raspberry pi

Error only happens sometimes - alexa responds and does things normally for a while, then suddenly doesn't anymore. Seems to happen when reactivated after long period of time, but I'm not sure.

Also, would we be able to reopen this?

**Comment by rbdedu** [comment]
I've got the same/similar error.
At first run everything worked fine, after 15 mins or so working got this exception, tried to restart the project, same problem.

**Comment by nberserk** [comment]
same here

**Comment by tweaty100** [comment]
@mkarliner @adrianmcli  @ajot @vamsijakkula  @peternann  @rbdedu @happyfrog99  
I am also faving this problem can you please tell me how to solve this problem as i am not getting any response back from Alexa whenever i asked any questions.please tell me as i am facing this problem since long

Thankyou in Advance
