### ISSUE TITLE
sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms method not found in client

### ISSUE THREAD

**Issue by halwebguy** [amzn/alexa-avs-raspberry-pi#169]
Getting this error when starting the client using mvn exec:exec.  I'm so close!  But I can't figure out what is happening here at all :(   Please help.

java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:337)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:199)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:152)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:72)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:64)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:59)
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:90)

**Comment by n0tf0und** [comment]
Same here
Alexa Voice Service - v20160207.0 opens
No popup for register with Amazon.

 mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-15" java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:337)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:199)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:152)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:72)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:64)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:59)
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:90)

**Comment by n0tf0und** [comment]
Using Pi 3 with Rasberian Jessie

**Comment by hunterchung** [comment]
I got the same error and was able to pass that by install the JDK from Oracle.
However, in the following web login step, I got error after accepting the agreement. Hopefully it is just a temp error from Amazon.
```
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
 Go to Amazon.com's Home Page
```

**Comment by hunterchung** [comment]
found the answer #5

**Comment by halwebguy** [comment]
Yes, it turns out version 8 is not enough.  I installed the latest and it resolved the issue.

**Comment by n0tf0und** [comment]
i upgraded to the latest version of Java at Oracle and everything started working.
My April 2016 version of Raspberian had 8.065 installed. I installed 8.0.91 to get things going.
I'm using a Pi 3 with a 64 bit processor but still must use the 32 bit Java.
After you get it working, download the app to configure Alexa to your area.
Use the same login as used for the developer site

**Comment by sshtel** [comment]
I upgraded java version to 1.8.0_91 and it works. Thanks.

**Comment by pjvksoft** [comment]
I also had the same error.
I solved it by adding the "appropriate Allowed return" URLs on the Amazon Developer Console website.

![solution](https://user-images.githubusercontent.com/10367876/36068739-ade54e3a-0edc-11e8-8c85-149d8d9b575e.png)
For my case it was "http://127.0.0.1:5000/code" instead of "http: // localhost: 5000 / code"
