### ISSUE TITLE
npm install - Throwing Error

### ISSUE THREAD

**Issue by mchamps** [amzn/alexa-avs-raspberry-pi#173]
When I attempt the npm install step (5 - Install the dependencies) I am getting the following error and npm doesn't run. Any ideas?

```
pi@raspberrypi:~/alexa/samples/companionService $ npm install

module.js:117
    throw e;
          ^
SyntaxError: Error parsing /usr/lib/node_modules/npm/node_modules/ansi/package.json: Unexpected string
    at Object.parse (native)
    at readPackage (module.js:113:52)
    at tryPackage (module.js:123:13)
    at Function.Module._findPath (module.js:190:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:3:12)
    at Module._compile (module.js:456:26)
```

**Comment by ajotwani** [comment]
@mchamps Make sure your package.json file is valid - http://jsonlint.com

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
