### ISSUE TITLE
Error:  "Exception in thread "main" java.lang.RuntimeException:  the KeyStore for contacting the companion service could not be loaded"

### ISSUE THREAD

**Issue by 4430salton** [amzn/alexa-avs-raspberry-pi#184]
Hello I am having the above error when executing the mvn exec:exec command.  up to this point everything appears to be working correctly.  my concern is I am using JAVA version "1.8.0_91" is this the problem?  does it have to be "1.8.0_77"?

Thanks for your Help!

**Comment by 4430salton** [comment]
excuse me I should say this is a new install and this is where it is failing.  this has not worked before

**Comment by erikhopf-amzn** [comment]
Can you provide additional details on the error you're encountering. If possible, attach a screenshot/logs. Thanks!

**Comment by ajotwani** [comment]
@4430salton Also, have you looked at this https://github.com/amzn/alexa-avs-raspberry-pi/issues/81?

**Comment by 4430salton** [comment]
Sorry for delay was out of town.

Hello ajotwani.  Yes ajotwani I have looked at that response and checked the config.json and it appears to be correct. i have not though put in the passphrase which is the same as password correct?

Hello erik,  here is the error that i am getting after I have got "npm start" started

-------------------------

pi@raspberrypi:~/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: The KeyStore for contacting the Companion Service could not be loaded.
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:131)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.<init>(CompanionServiceClient.java:67)
at com.amazon.alexa.avs.auth.AuthSetup.startProvisioningThread(AuthSetup.java:81)
at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
Caused by: java.io.IOException: keystore password was incorrect
at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2015)
at java.security.KeyStore.load(KeyStore.java:1445)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:110)
... 5 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
... 8 more
---------------------------------------------

**Comment by swasey-amzn** [comment]
@4430salton I would suggest you re-generate your certificates for the companion service and make sure to keep track of the passphrase you enter. You don't even necessarily need to enter a passphrase, and can just leave it blank.

**Comment by 4430salton** [comment]
"re-generate your certificates for the companion service" which means to run this command again "./generate.sh" correct?

**Comment by swasey-amzn** [comment]
@4430salton That is correct.

**Comment by 4430salton** [comment]
Nope still getting the same error:
pi@raspberrypi:~/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: The KeyStore for contacting the Companion Service could not be loaded.
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:131)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.<init>(CompanionServiceClient.java:67)
	at com.amazon.alexa.avs.auth.AuthSetup.startProvisioningThread(AuthSetup.java:81)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
Caused by: java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2015)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:110)
	... 5 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
	... 8 more

**Comment by 4430salton** [comment]
BTW I am sending this info from my raspberrypi that is having the problem.

**Comment by swasey-amzn** [comment]
1. Does the folder "certs" exist alongside generate.sh after running it? If you could run "find certs/", that'd be helpful.
2. Could you show your config.json file (if you put in a passphrase, you can redact it, but make sure it was 100% correct)
3. Did you enter a passphrase when running generate.sh? Or did you just hit enter to pass through?

**Comment by 4430salton** [comment]
Does the folder "certs" exist alongside generate.sh after running it? there is a folder called certs under the javaclient directory.  when i run your command i get this below

pi@raspberrypi:~/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient $find certs/
certs/
certs/ca
certs/ca/ca.key
certs/ca/ca.crt
certs/ca/ca.der
certs/client
certs/client/client.csr
certs/client/client.key
certs/client/client.pkcs12
certs/client/client.crt
certs/server
certs/server/jetty.csr
certs/server/jetty.pkcs12
certs/server/client.pkcs12
certs/server/jetty.key
certs/server/node.key
certs/server/node.csr
certs/server/node.crt
certs/server/jetty.crt

Could you show your config.json file? the last time a ran ./generate.sh i did not use a password

{
    "productId":"my_device",
    "dsn":"123456",
    "provisioningMethod":"companionService",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"/home/pi/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"/home/pi/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"/home/pi/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient/certs/ca/ca.crt"
    }
}
s



Did you enter a passphrase when running generate.sh? Or did you just hit enter to pass through?
no i just hit enter and pass on through

**Comment by 4430salton** [comment]
no reponse so I am rebuilding the sucka again.  later

**Comment by swasey-amzn** [comment]
Hey @4430salton, sorry for the slow response. Your certs are incorrect for some reason. There shouldn't exist a "certs/server/client.pkcs12" file, so I'm not sure how that exists for you. If you could nuke the "certs" folder and regenerate them all, and then update your config.json file to this value:
...
"sslClientKeyStore":"/home/pi/Downloads/avs_master/alexa-avs-raspberry-pi-master/samples/javaclient/certs/**client**/client.pkcs12",
...

I think it should work.

**Comment by 4430salton** [comment]
Thanks swasey but i have nuked the whole thing.  i will rebuild it again.
the more I do it the more stuff i will figure out.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
