### ISSUE TITLE
Client Crash After "Device Tokens Ready"

### ISSUE THREAD

**Issue by rgruskin** [amzn/alexa-avs-raspberry-pi#191]
I am getting a crash in the client after I press ok to the  on the dialog with the URL after Device Tokens are ready.  Here is the trace:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
20:35:38.822 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
java.lang.RuntimeException: The required file config.json could not be updated.
	at com.amazon.alexa.avs.config.DeviceConfigUtils.updateConfigFile(DeviceConfigUtils.java:146) ~[classes/:?]
	at com.amazon.alexa.avs.config.DeviceConfig.saveConfig(DeviceConfig.java:204) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:59) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:90) [classes/:?]
Caused by: java.io.FileNotFoundException: config.json (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_91]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_91]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_91]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101) ~[?:1.8.0_91]
	at com.amazon.alexa.avs.config.DeviceConfigUtils.updateConfigFile(DeviceConfigUtils.java:131) ~[classes/:?]
	... 5 more

I checked the permissions on the config.json file:
  -rwxr-xr-x 1 root root  668 May 13 22:42 config.json

i  tried the sudo env PATH=$PATH" command suggested in case #131 without any luck.

I have been looking at this for two days now and i would appreciated any help!

**Comment by rgruskin** [comment]
Nevermind...my permissions were wrong.  chmod 777 fix it.  It's working!
