### ISSUE TITLE
mvn exec:exec fails

### ISSUE THREAD

**Issue by nagasriswetha** [amzn/alexa-avs-raspberry-pi#196]
I mvn validate and mvn install with success, however upon running mvn exec:exec in the samples/javaclient directory, it fails at the following:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 10 at (line no=2, column no=29, offset=30)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:189)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:376)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:255)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:177)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:60)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:46)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.273 s
[INFO] Finished at: 2016-06-03T18:01:00+05:30
[INFO] Final Memory: 10M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Here's my config.json file:

{
    "productId”:”my_device”,
    "dsn”:”123456”,
    "provisioningMethod":"companionApp",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore”:”/Users/Test/Downloads/AlexaVoiceServiceExamples/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase”:”password”,
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore”:”/Users/Test/Downloads/AlexaVoiceServiceExamples/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase”:”password”,
        "sslCaCert”:”/Users/Test/Downloads/AlexaVoiceServiceExamples/samples/javaclient/certs/ca/ca.crt"
    }
}

**Comment by keleric** [comment]
Your quotes in config.json are incorrect. See the difference between the quotes around my_device and the quotes around companionApp

**Comment by ajotwani** [comment]
Closing as answered.
