### ISSUE TITLE
mvn exec:exec  problem

### ISSUE THREAD

**Issue by HillClimberNW** [amzn/alexa-avs-raspberry-pi#215]
I just bought a new rpi3 and was using the github project https://github.com/amzn/alexa-avs-raspberry-pi to setup Alexa voice service.

At the "mvn exec:exec" point, I got unexpected results. The following shows the command window contents and at the bottom of that is the description of the window that popped up. It looks like the one after you complete steps 10.1 - 10.5.

As a note, I did have a little concern with the Java install in step 2.6. it looks like the SD card with Raspian that came with the rpi3 already had Java. After installing the latest JDK anyway and some experimenting, I chose to select the alternative number of the preexisting install.

Can someone point me in the right direction, please?

It's been a long time since I've done Linux. But I have IT background and am fairly savvy.

thanks for any help...

pi@raspberrypi:~/Apps/alexa-avs-raspberry-pi-master/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-15" java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:337)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:199)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:152)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:72)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:64)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:59)
at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:90)

App window appears and has Title of "Alexa Voice Service = v20160207.0
First Line: "Device: my_device DSN:123456", a blank line, and "Bearer Token""
below, it says "Start Listening"
at the bottom, three buttons, "|<-", play/pause symbols, "->|"

**Comment by TechnohKiller** [comment]
I had the same problem and fixed it by updating java
Go back to step 4.3 and run those steps
then I think you need to make sure your device ID is in the config files

**Comment by HillClimberNW** [comment]
Thanks.  I finally got back to this project.   I went through the 4.3 steps again and got past my error. 

 

I have a new one but I’ll post that back on the forum

 

Thanks again for the help.

 

Kevin
