### ISSUE TITLE
Problem at step 8 - npm start

### ISSUE THREAD

**Issue by prumyancev** [amzn/alexa-avs-raspberry-pi#225]
Hi,
I faced with a such problem during execution step 9 - npm start. Such error in terminal: 
$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory ''
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log

And log file contain:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
11 verbose cwd /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService
12 error Linux 4.1.19+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.6
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls alexa-voice-service-sample-companion-service
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

I will be very appreciate for the help,
Regards,
Pavlo

**Comment by ajotwani** [comment]
@prumyancev you still having issues with this?

**Comment by thehellgod** [comment]
Hey @ajotwani ,
I was trying the raspberry install today and am facing this issue

**Comment by dshachtman** [comment]
Hey @ajotwani ,
I just got stuck at the same point trying to run npm start.  Any thoughts?

**Comment by ajotwani** [comment]
@prumyancev @thehellgod @dshachtman We've updated this project to include hands-free voice activation, using wake word engines from Sensory or KITT.AI. So, in addition to pushing a button to "start listening", you can now also just say the wake word "Alexa", much like the Amazon Echo. 

Perhaps give it another whirl, and let us know how it goes?

**Comment by dleybz** [comment]
Having the same error with the `npm start` in step 7

**Comment by keleric** [comment]
Can you paste your config.js file from the companion service? (Replace your client secret / client id last few digits with XXX)

**Comment by krisnaw** [comment]
Any solution for this? I have got the same exact error

**Comment by stevbenn** [comment]
@smachaje: It seems like your issue is due to `interactive-adventure-game-tool` which is not related to Alexa Sample App.  Could you try 
``` bash 
npm update -g
```
to update your `npm` packages.

@krisnaw: Could you include an output of your terminal so we can understand your issue better?
