### ISSUE TITLE
Error after clicking "Start Listening"

### ISSUE THREAD

**Issue by HillClimberNW** [amzn/alexa-avs-raspberry-pi#228]
below is what's displayed in the terminal window.  and there's the word "Error" in the window header, a red stopsign, and a "OK" button showing...
I have the recommended usb mic and the speaker.
I have followed the github page and recently redid section 4.3 to fix a Java issue. Java version is now 1.8.0_91

Any help is appreciated.... Kevin

pi@raspberrypi:~/Apps/alexa-avs-raspberry-pi-master/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
00:25:00.723 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
java.lang.NullPointerException
	at com.amazon.alexa.avs.AudioCapture.startCapture(AudioCapture.java:74) ~[classes/:?]
	at com.amazon.alexa.avs.AudioCapture.getAudioInputStream(AudioCapture.java:56) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:167) [classes/:?]
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:204) [classes/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_91]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_91]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_91]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_91]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_91]
	at java.awt.Component.processMouseEvent(Component.java:6535) [?:1.8.0_91]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_91]
	at java.awt.Component.processEvent(Component.java:6300) [?:1.8.0_91]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_91]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) [?:1.8.0_91]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_91]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_91]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_91]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_91]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_91]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_91]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [?:1.8.0_91]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_91]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_91]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_91]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_91]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_91]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_91]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_91]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_91]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_91]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_91]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_91]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_91]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_91]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_91]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_91]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_91]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_91]

**Comment by HillClimberNW** [comment]
I got past this issue.  I'm not entirely sure what fixed it.   changed microphone, set up audio devices properly, and ran mvn install again.     closing this one.
