### ISSUE TITLE
Error on dev authorization (Step 10)

### ISSUE THREAD

**Issue by josephcera** [amzn/alexa-avs-raspberry-pi#5]
Server is up, Build was successful. I sign in on Amazon and am redirected to the dev authorization page as expected. After clicking OK, there's an error processing my request. (Amazon error page) I completed all steps for the Amazon security profile and entered both my client ID and client secret as instructed.

**Comment by ctbartolillo** [comment]
I am having the same problem, any luck fixing it?

**Comment by ctbartolillo** [comment]
Figured it out.  You have to make sure the device Id you put into amazon is my_device or it will not work correctly.

**Comment by josephcera** [comment]
Confirmed this worked. Had to register a new product type though via https://developer.amazon.com/edw/home.html#/avs/list make sure to select the correct security profile. Thanks @ctbartolillo 

when you're done, it should look like this
![image](https://cloud.githubusercontent.com/assets/15039377/14058103/478ea22a-f2ec-11e5-9f4d-2c2885ed29bb.png)

**Comment by aManFromOuterSpace** [comment]
Instructions work just fine for the Pi 1 Model B. Great stuff.

**Comment by chrispc05** [comment]
I did what @josephcera recommended and I now get the message: "unknown client id" when I try to register. Hmmm....do I need to go back to 3.4 and start registration again, or is there some way to sync the new device id that I missed?

**Comment by Flashpointmix** [comment]
Anyone get this working?? I'm losing my mind here, i get all the way to the web browser bit, and then i get a privacy error, type in badidea and then i get through the amazon login stuff and click ok and then BOOM i get slammed with an error message, Would love any fixes or tips on this project.

**Comment by mdnegan** [comment]
having same issues,one of the things i have done extra not mentioned here,even tho i bet some of you have done it ,just not mentioned is is opened up ports n confirmed listening port has connected to amazon,which is yes

**Comment by mdnegan** [comment]
two possible leads on what is causing the issue 
one is after running the automated_install.sh

chown: cannot access ‘/home/root/.asoundrc’: No such file or directory

the other is after running mvn exec:exec


[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
2016-10-19 00:01:35,675 ERROR FileManager (logs/application.log) java.io.FileNotFoundException: logs/application.log (Permission denied)
2016-10-19 00:01:35,688 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:137)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:766)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:706)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:698)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:358)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:361)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:426)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:442)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:102)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
	at com.amazon.alexa.avs.AVSApp.<clinit>(AVSApp.java:58)
Caused by: java.lang.IllegalStateException: Unable to create a manager
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:60)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:79)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:184)
	... 24 more

2016-10-19 00:01:35,767 ERROR Null object returned for RollingFile in Appenders.
2016-10-19 00:01:35,813 ERROR Unable to locate appender file for logger 

** (epiphany-browser:29804): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

**Comment by clarkm** [comment]
banged my head on this for a longgg time, and finally found a FIX!! I was incorrectly putting in the Security Profile ID (amzn1.application.0cexxxxxxx) string as the ProductID instead of the device name itself (my_device). This led to the “An error occured when we tried to process your request.” page. I just changed the string in the automated_install.sh and now everything is working on my raspberry pi 1!! Thanks - hopefully this helped someone!

**Comment by xavier630** [comment]
@clarkm 

This solution was perfect. They give you the three fields when you sign up, so I assumed that it would ask for the same three fields and copied and pasted without paying too much attention.

Thank you for saving me a lot of trouble!

**Comment by nbibin001** [comment]
@clarkm I am facing the same issue , and was trying to apply the fix you mentioned. So does that mean that we have to create/register a new product type from the beginning and give it a name like "my_device" and use the same as the product id in the automated_install.sh and repeat the whole process ? Really appreciate your help.

**Comment by xavier630** [comment]
@nbibin001 

You know how when you run that install script and it asks for 3 things within the terminal editor? Basically, the first of those should be your product id, which is this name:

![image](https://cloud.githubusercontent.com/assets/9077250/19753984/c3dd4692-9c65-11e6-8a8b-9687bd6a96e8.png)

**Comment by pi2bone** [comment]
thanks man you are genius

**Comment by ZwoRmi** [comment]
I made the mistake too. Is it needed to re-execute `automated_install.sh` after fixing the `ProductID`?

**Comment by Alexnagel** [comment]
@ZwoRmi Yes you'd need to do that

**Comment by TeamKalis** [comment]
Still having this issue after numerous fixes.

**Comment by xxtechwreck** [comment]
I am not able to get past the "We're sorry! An error occurred when we tried to process your request." message. I have changed the ProductID to the Display name/ everything I have because i named them all the same thing.

**Comment by TeamKalis** [comment]
Still having this issue as of 4/17/23  I need help.

**Comment by robododge** [comment]
**SOLVED**. As with everyone else, I ran into this problem after completing the full setup and build.  I just solved this locally with my raspberry pi sample app.  And, NO, you do not have to name your device "my_device".

1. I found a typo in my device name:  PI3 locally, but on AWS security profile, Device Type ID = Pi3.  Made sure the Device: field in the top left of your java client matches the Device Type ID or just "ID" in your AWS Alexa Voice Service List.
2. Set about to rebuild my local environment fixing the typo to match the security profile I on AWS
3. edit alexa-avs-sample-app/samples/companionService/config.js  changed to "Pi3" 
```
products: {
   Pi3: ["123456789"],
}
```

4. Edit 2 files in the javaclient.  alexa-avs-sample-app/samples/javaclient/config.json and alexa-avs-sample-app/samples/javaclient/generate.sh  Changed everything to match the correct device name "Pi3"
5. re-run the javaclient directory's generate.sh, this will rebuild ssl key/value pairs in the java keystore
6. start the node client again, then start the java client again.  Should not see any errors
7. open the web browser with the newly generated provision URL posted in the modal dialog of the java client
8. you should see a web page with "device tokens ready"

**Comment by amark14912** [comment]
@robododge This works very well. This even removed my problem with hotword detection.

**Comment by embeddednerd** [comment]
Thanks to my habit of reading all the comments first, before implementing the fix 
clarkm commented on Oct 21, 2016 works superb

**Comment by rosariomartone** [comment]
Guys,
I have lost my patience with this error... :)
I have created the my_device stuff but still getting the error:


We're sorry!An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

After I inserted my username and pwd. Any idea???

Thanks!

**Comment by manojcena** [comment]
Hi i also facing the same error while login with amazon but i came to know that i need to add device details. but i am unable to find where to update the device details. can any one help me out to solve the problem.

**Comment by Lirong6** [comment]
hi, 
  I encounter this problem too. even though I type the client ID correctly, it will have this error. the solution is to just copy and paste the relevant information in your amazon developer page and redo all the following process again including install process. I think maybe this is because it has some format limit.

**Comment by hannan112** [comment]
hi i am facing this problem pls help me
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.

**Comment by hannan112** [comment]
![capture](https://user-images.githubusercontent.com/41451097/43357148-0410b4a6-9232-11e8-97ed-70434b6a3d67.JPG)
