### ISSUE TITLE
npm start issues

### ISSUE THREAD

**Issue by DomDale** [amzn/alexa-avs-raspberry-pi#63]
I have set up the whole thing up to when you type npm start but when I do I get these errors:
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexavoiceserviceexamples/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pi/alexvoiceserviceexamples/samples/javaclient/certs/server/node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/pi/alexavoiceserviceexamples/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/alexavoiceserviceexamples/samples/companionService/npm-debug.log

My debug log is:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/alexavoiceserviceexamples/samples/companionService/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/l$
10 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: /home/pi/alexavoiceserviceexamples/samples/companionService
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
14 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
16 verbose cwd /home/pi/alexavoiceserviceexamples/samples/companionService
17 error Linux 4.1.19-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v5.9.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs alexa-voice-service-sample-companion-service
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls alexa-voice-service-sample-companion-service
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Hope someone can help!

**Comment by PClough** [comment]
check the ssl.cnf as per [here](https://github.com/amzn/alexa-avs-raspberry-pi/issues/59). Also check the spelling, quotation mark positions and paths in all of step 4.

**Comment by DomDale** [comment]
Tried all of that still no luck, any other ideas?

**Comment by cwilkes** [comment]
The log says that the `/home/pi/alexvoiceserviceexamples/samples/javaclient/certs/server/node.key` file is missing.  Is there one there?  It should start with a line like `-----BEGIN RSA PRIVATE KEY-----`   That file's created when you run the `javaclient/generate.sh` script.

**Comment by PClough** [comment]
@DomDale - Think I've got it. The error on you have presented shows this line  - '/home/pi/alexvoiceserviceexamples/samples/javaclient/certs/server/node.key'

alexa has an 'a' on the end lol. You've said 'alexvoiceserviceexamples'. - I said it would be a spelling mistake.

**Comment by rayymlai** [comment]
I encounter "Cannot find module ./types.json" exception when running "npm start" (step 8). Any pointer? Thanks.

I've completed installation steps up to step 7.  I used the product id "echo" instead of "myDevice". My ssl.cnf uses 2-letter country code "US". 

## Installation Details
```
pi@echo01:~/dev/alexa-avs-raspberry-pi/samples/companionService $ node --version
v0.10.44

pi@echo01:~/dev/alexa-avs-raspberry-pi/samples/companionService $ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) Client VM (build 25.77-b03, mixed mode)
```
## Error Details
```
pi@echo01:~/dev/alexa-avs-raspberry-pi/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/dev/alexa-avs-raspberry-pi/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.


module.js:340
    throw err;
          ^
Error: Cannot find module './types.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/dev/alexa-avs-raspberry-pi/samples/companionService/node_modules/express/node_modules/send/node_modules/mime/mime.js:87:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dev/alexa-avs-raspberry-pi/samples/companionService/npm-debug.log
```

**Comment by burf2000** [comment]
I have the same issue, Error: ENOENT, no such file or directory '~/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.key' 

but that's a completely valid path to the cert, nano to it works

**Comment by burf2000** [comment]
Done use ~ use /home/pi/

**Comment by DomDale** [comment]
@PClough was right! it was a typo

**Comment by cheersalam** [comment]
I was getting `Error: ENOENT, no such file or directory '/home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient/cwqerts/ca/ca.crt'` 

Found that cwqerts folder was missing in samples/javaclient folder. There was certs folder instead, So I copied it to cwqerts and after that it started working

**Comment by phelps-oc** [comment]
Getting this when i run npm start


npm ERR! Error: ENOENT, open '/home/pi/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.21-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

Any ideas? There is no package.json file i /home/pi
