### ISSUE TITLE
The KeyStore for contacting the Companion Service could not be loaded

### ISSUE THREAD

**Issue by jeremiahtorres** [amzn/alexa-avs-raspberry-pi#81]
Everything was going great until the last step in step 9.
here is what i get when I get to the final step:

`pi@raspberrypi:~/Downloads/alexa/samples/javaclient $ mvn exec:exec -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: The KeyStore for contacting the Companion Service could not be loaded.
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:131)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.<init>(CompanionServiceClient.java:67)
at com.amazon.alexa.avs.auth.AuthSetup.startProvisioningThread(AuthSetup.java:81)
at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
Caused by: java.io.IOException: keystore password was incorrect
at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2015)
at java.security.KeyStore.load(KeyStore.java:1445)
at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getPinnedSSLSocketFactory(CompanionServiceClient.java:110)
... 5 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
... 8 more
`
so I checked to make sure, I didn't miss anything.

This one is a head scratcher. please help

**Comment by duncangeere** [comment]
I just came across this issue and fixed it by checking my config.json - I had the wrong passphrase written there. Once I corrected that, it worked.

**Comment by ajotwani** [comment]
Added an FAQ for "Companion Service" errors. See https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors

**Comment by altitudeinfosys** [comment]
I created a brand new device - under the amazon developer console and that's fixed my problem.. I was having the same issue.
